# Breast cancer

bc:

    zzmap_bc:
        method: "zz"
        epochs: 200
        positive_factor: 1
        depth: 1
        seed: 10598

    qrac_bc:
        method: "qrac"
        epochs: 200
        positive_factor: 1
        depth: 1
        seed: 10598

    te_bc:
        method: "te"
        epochs: 200
        positive_factor: 1
        depth: 1
        seed: 700

    te_reg_bc:
        method: "te"
        epochs: 200
        positive_factor: 1
        depth: 1
        seed: 666
        reg: 0.02

# Titanic

ts:

    zzmap_dis_ts:
        method: "zz_dis"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 10598

    zzmap_dis_cont_ts:
        method: "zz_dis_cont"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 10598

    qrac_ts:
        method: "qrac"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 10598

    qrac_zz_ts:
        method: "qrac_zz"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 10598

    te_ts:
        method: "te"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 10598

    te_reg_ts_20:
        method: "te"
        epochs: 20
        positive_factor: 0.33
        depth: 4
        seed: 666
        reg: 0.02

    te_reg_ts_real:
        method: "te"
        epochs: 100
        positive_factor: 0.33
        depth: 4
        seed: 666
        reg: 0.02
        real_device: True

    te_reg_ts:
        method: "te"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 666
        reg: 0.02

    te_zz_ts:
        method: "te_zz"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 666

    te_zz_reg_ts:
        method: "te_zz"
        epochs: 300
        positive_factor: 0.33
        depth: 4
        seed: 666
        reg: 0.02

# MNIST
mnist:
    16px_mnist:
        method: "16px"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

    8px_mnist:
        method: "8px"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

    qrac_mnist:
        method: "qrac"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

    conv_mnist:
        method: "conv"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

    conv_te_mnist:
        method: "conv_te"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

    conv_41_mnist:
        method: "conv_41"
        epochs: 10
        depth: 1
        seed: [111,222,333,444,555]

# Parity check 3,6,9
pc_3:
    naive_pc:
        method: "naive"
        epochs: 200
        depth: 4
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_pc:
        method: "qrac"
        epochs: 200
        depth: 4
        dup: 1
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup2_pc:
        method: "qrac"
        epochs: 200
        depth: 4
        dup: 2
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup3_pc:
        method: "qrac"
        epochs: 200
        depth: 4
        dup: 3
        seed: [111,222,333,444,555,666,777,888,999,1111]

pc_6:
    naive_pc:
        method: "naive"
        epochs: 200
        bit: 6
        depth: 4
        seed: [111,222,333,444,555,666,777,888,999,1111]

    te_pc_real_device:
        method: "te"
        epochs: 400
        bit: 6
        depth: 4
        dup: 1
        seed: [111]
        real_device: True

    te_pc:
        method: "te"
        epochs: 400
        bit: 6
        depth: 4
        dup: 1
        seed: [111,222,333,444,555]

    qrac_pc:
        method: "qrac"
        epochs: 200
        bit: 6
        depth: 4
        dup: 1
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup2_pc:
        method: "qrac"
        epochs: 200
        bit: 6
        depth: 4
        dup: 2
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup3_pc:
        method: "qrac"
        epochs: 200
        bit: 6
        depth: 4
        dup: 3
        seed: [111,222,333,444,555,666,777,888,999,1111]

pc_9:
    naive_pc:
        method: "naive"
        epochs: 200
        bit: 9
        depth: 4
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_pc:
        method: "qrac"
        epochs: 200
        bit: 9
        depth: 4
        dup: 1
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup2_pc:
        method: "qrac"
        epochs: 200
        bit: 9
        depth: 4
        dup: 2
        seed: [111,222,333,444,555,666,777,888,999,1111]

    qrac_dup3_pc:
        method: "qrac"
        epochs: 200
        bit: 9
        depth: 4
        dup: 3
        seed: [111,222,333,444,555,666,777,888,999,1111]
